### PR TITLE
Some minor error fixes

### LINKED ISSUE #47: Code formatting (C.7.1)
### C.7.1   Solution to: Positive Matches

Missing code block formatting:

image

### PR DESCRIPTION
**Pull request by floating-cat**
Also fix #47

### CODE REVIEW

**Comment by ghisvail** [comment]
@floating-cat Did you check whether your fixes addressed some of the current [issues](https://github.com/underscoreio/essential-scala/issues)? Thanks.

**Comment by floating-cat** [comment]
I checked those issues. I only fixed https://github.com/underscoreio/essential-scala/issues/47.
Also I found two issues (https://github.com/underscoreio/essential-scala/issues/40 https://github.com/underscoreio/essential-scala/issues/50) has already been fixed in master branch. Because I found these two issues too when I read this book.

**Comment by ghisvail** [comment]
Then you might want to tag these issues in your commit message to close them automatically on merge.

**Comment by floating-cat** [comment]
Thanks for you suggestion (Actually my PR is earlier than that issue), I updated my comment, now referenced issue will automatically be closed when this PR is merged.

**Comment by davegurnell** [comment]
Thanks! I'll merge these. Note, however, that some of these files are cut content that doesn't actually appear in the book!

**Pull request merged**
